server:
  port: 8081
  servlet:
    context-path: /user-service-service

spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: user-service-service
    version: 1.0-SNAPSHOT
  jmx:
    default-domain: lms-userservice-domain
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: admin

feign:
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000